### PR TITLE
Don't require setting all values, fix #5

### LINKED ISSUE #5: Force close when not supplying all options to SimpleSlide.Builder
Crashes in Fragment constructor when loading Resource ids from Fragment arguments, as some of them are 0x0.

### PR DESCRIPTION
**Pull request by Maxr1998**

### CODE REVIEW

File: library/src/main/java/com/heinrichreimersoftware/materialintro/slide/SimpleSlide.java [hunk 1]
```diff
@@ -145,28 +143,31 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
...
-            if(ColorUtils.calculateLuminance(background) > 0.6){
+            if (backgroundRes != 0 && ColorUtils.calculateLuminance(ContextCompat.getColor(getContext(), backgroundRes)) > 0.6) {
                 //Use dark text color
                 title.setTextColor(ContextCompat.getColor(getContext(),
                         R.color.mi_text_color_primary_light));
                 description.setTextColor(ContextCompat.getColor(getContext(),
                         R.color.mi_text_color_secondary_light));
-            }
-            else {
+            } else {
```
Comment (HeinrichReimer) [inline library/src/main/java/com/heinrichreimersoftware/materialintro/slide/SimpleSlide.java]: This should be `else if(backgroundRes != 0)`

**Comment by HeinrichReimer** [comment]
See line note

**Comment by HeinrichReimer** [comment]
@Maxr1998 Please edit the line I commented on. It's the only thing keeping me away from merging this pull request.

**Comment by HeinrichReimer** [comment]
Fixes #5
